services:
  - type: web
    name: face-recognition-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://mahadevags573:AHvkbkxaUmVZsEzS@madeva1.dry8zrf.mongodb.net/?retryWrites=true&w=majority
      - key: MONGO_DB_NAME
        value: attendance_db
      - key: MONGO_COLLECTION_NAME
        value: attendance
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
